apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-agent
  labels:
    app: custom-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-agent
  template:
    metadata:
      labels:
        app: custom-agent
    spec:
      containers:
      - name: custom-agent
        image: custom-agent:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: custom-agent
spec:
  selector:
    app: custom-agent
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
