apiVersion: apps/v1
kind: Deployment
metadata:
  name: crew-agent
  labels:
    app: crew-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crew-agent
  template:
    metadata:
      labels:
        app: crew-agent
    spec:
      containers:
      - name: crew-agent
        image: crew-agent:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: agent-configmap
        - secretRef:
            name: agent-secrets
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: crew-agent
spec:
  selector:
    app: crew-agent
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
