apiVersion: v1
kind: Secret
metadata:
  name: agent-secrets
type: Opaque
data:
  API_KEY: <base64-encoded-value>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-configmap
data:
  BASE_URL: <base-url-value>
