apiVersion: v1
kind: Secret
metadata:
  name: agent-secrets
type: Opaque
data:
  API_KEY: <base64-encoded-value>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-configmap
data:
  BASE_URL: <base-url-value>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bee-agent
  labels:
    app: bee-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bee-agent
  template:
    metadata:
      labels:
        app: bee-agent
    spec:
      containers:
      - name: bee-agent
        image: bee-agent:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: agent-configmap
        - secretRef:
            name: agent-secrets
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bee-agent
spec:
  selector:
    app: bee-agent
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crew-agent
  labels:
    app: crew-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crew-agent
  template:
    metadata:
      labels:
        app: crew-agent
    spec:
      containers:
      - name: crew-agent
        image: crew-agent:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: agent-configmap
        - secretRef:
            name: agent-secrets
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: crew-agent
spec:
  selector:
    app: crew-agent
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
