apiVersion: v1
kind: Secret
metadata:
  name: bee-agent-secrets
type: Opaque
data:
  API_KEY: <base64-encoded-value>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bee-agent-configmap
data:
  BASE_URL: <base-url-value>
  PROMPT: What's the current weather in New York?
---
apiVersion: batch/v1
kind: Job
metadata:
  name: bee-agent
spec:
  template:
    metadata:
      name: bee-agent
    spec:
      containers:
      - name: bee-agent
        image: agent:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: bee-agent-configmap
        - secretRef:
            name: bee-agent-secrets
      restartPolicy: OnFailure
